spring.application.name=ObraControl

spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:obracontrol}
spring.datasource.username=${DB_USER:obracontrol}
spring.datasource.password=${DB_PASSWORD:obracontrol}

spring.flyway.enabled=true
